import { Authentication } from './Authentication'

export class JWTAuthentication implements Authentication {
  /**
   * Creates a new token authentication
   *
   * @param secret a token generated by the SDK
   */
  constructor(public readonly token: string) {}

  /**
   * Attaches an Authorization header
   *
   * @returns the headers for the request
   */
  public createHeaders(): Record<string, string> {
    return {
      Authorization: `Bearer ${this.token}`,
    }
  }
}
